import Head from "next/head";
import { poppins, montserrat, inter } from "@/utils/fonts";
import Header from "@/components/header";
import styles from "@/styles/Home.module.scss";
import Package from "@/components/package";

export default function Home() {
  const partners = [
    "/images/partner1.png",
    "/images/partner2.png",
    "/images/partner3.png",
    "/images/partner4.png",
    "/images/partner5.png",
    "/images/partner6.png",
    "/images/partner7.png",
    "/images/partner8.png",
  ];

  const awards = [
    "/images/award1.png",
    "/images/award2.png",
    "/images/award3.png",
    "/images/award4.png",
    "/images/award5.png",
    "/images/award6.png",
    "/images/award7.png",
    "/images/award8.png",
  ];

  const packages = [
    {
      title: "basic",
      price: 199,
    },
    {
      title: "standard",
      price: 649,
    },
    {
      title: "professional",
      price: 749,
    },
    {
      title: "premium",
      price: 1800,
    },
    {
      title: "titanium",
      price: 2300,
    },
    {
      title: "diamond",
      price: 2800,
    },
  ];

  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.header}>
        <Header />
      </div>
      <main className={`${styles.main}`}>
        {/* SECTION ONE */}
        <section className={styles.section_one}>
          <div className="container container-xxl container-xl">
            <div className="row">
              <div className="col-lg-7 col-md-7 col-sm-12">
                <div className={styles.hero_content_wrapper}>
                  <div className={styles.subheading}>
                    <span>Be Successful One</span>
                  </div>
                  <h1 className={styles.hero_title}>
                    We Knows How to Win Clients, Grow Traffic, Increase Sales &
                    Maximize Profitability For You!
                  </h1>
                  <p className={styles.hero_des}>
                    Our proven SEO delivers you more rankings, more traffic, and
                    more customers.
                  </p>
                  <div className={styles.hero_content_inner}>
                    <form
                      action="#"
                      className={`${styles.hero_form} ${poppins.className}`}
                    >
                      <div className="row g-0" style={{ marginBottom: "10px" }}>
                        <div className="col-lg-4">
                          <input
                            type="text"
                            className="form-control"
                            placeholder="Your Name"
                          />
                        </div>
                        <div className="col-lg-4">
                          <input
                            type="email"
                            className="form-control"
                            placeholder="Your Email"
                          />
                        </div>
                        <div className="col-lg-4">
                          <input
                            type="tel"
                            className="form-control"
                            placeholder="Your Phone Number"
                          />
                        </div>
                      </div>
                      <div className="row  g-0">
                        <div className="col-8">
                          <input
                            type="text"
                            className="form-control"
                            placeholder="Your Website URL"
                          />
                        </div>
                        <div className="col-4">
                          <button>SUBMIT</button>
                        </div>
                      </div>
                    </form>

                    <div className={styles.hero_partners}>
                      {partners.map((item, index) => {
                        return (
                          <img src={item} key={index} className="img-fluid" />
                        );
                      })}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* SECTION TWO */}
        <section className={styles.section_two}>
          <div className="container">
            <div className={styles.awards_wrapper}>
              {awards.map((item, index) => {
                return <img src={item} key={index} className="img-fluid" />;
              })}
            </div>
          </div>
        </section>

        {/* SECTION THREE */}
        <section className={`${styles.section_three} ${poppins.className}`}>
          <div className="container">
            <div className="row g-5">
              <div className="col-lg-7">
                <div className={styles.section_three_content}>
                  <h2>
                    Want to improve your ROI? Drive more organic traffic to your
                    website.
                  </h2>
                  <p>
                    Get more qualified traffic on the search terms that matter
                    most to your business. We analyze every variable that
                    affects SERPs, from domain authority to site speed –
                    allowing us to achieve results that matter. SmartSites has a
                    proven track record. Set your business up for long-term
                    success today!
                  </p>
                  <h4>
                    <span>200%</span>Most of our SEO campaigns double their
                    traffic within 6 months.
                  </h4>
                  <form
                    action="#"
                    className={`${styles.section_three_form} ${montserrat.className}`}
                  >
                    <div className="row g-3">
                      <div className="col-7">
                        <input
                          type="email"
                          placeholder="Enter your website"
                          className="form-control"
                        />
                      </div>
                      <div className="col">
                        <button>
                          Send me a proposal{" "}
                          <img
                            src="/images/angle.png"
                            alt="angle_icon"
                            className="img-fluid"
                          />
                        </button>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
              <div className="col-lg-5 align-self-center">
                <div className={styles.chart_img}>
                  <img
                    src="/images/chart-img.png"
                    alt="chart_img"
                    className="img-fluid"
                  />
                </div>
              </div>
            </div>
          </div>
        </section>

        <div className={styles.lines_bg}>
          {/* SECTION FOUR */}
          <section className={`${styles.section_four} ${poppins.className}`}>
            <div className="container">
              <div className="row">
                <div className="col-12">
                  <div className={styles.section_four_title}>
                    <h2>Why SEO Is Necessary For Business?</h2>
                    <div className={styles.more_sales}>
                      <span>More Sales, More Revenue & More Profitability</span>
                    </div>
                    <h3>
                      That’s Why You Need to Be On the{" "}
                      <span>1st Page of Google</span>
                    </h3>
                  </div>
                </div>
              </div>
              <div className="row g-3">
                <div className="col-lg-3">
                  <div className={styles.testimonial}>
                    <img
                      src="images/quote-red.png"
                      alt="quote-red"
                      className={`${styles.quote_img} img-fluid`}
                    />
                    <img
                      src="images/client.png"
                      alt="client"
                      className={`${styles.client_img} img-fluid`}
                    />
                    <p>
                      This company provided me with the best website design
                      services I have ever come across. Not only is my website
                      now more modern and visually appealing, but it’s also much
                      easier to use. Highly recommend this company!
                    </p>
                    <h4>Jackson Davis</h4>
                  </div>
                </div>
                <div className="col">
                  <div className={styles.poor_website}>
                    <div className={styles.poor_website_title}>
                      <h2>
                        Atleast 88% of visitors go with a competitor, after a{" "}
                        <span className={styles.underline}>poor website</span>{" "}
                        experience.
                      </h2>
                    </div>
                    <ul>
                      <li>
                        Google is responsible for <span>95%</span> of all search
                        traffic.
                        <br /> <span>90% of people</span> never go past the
                        first page of search results.
                      </li>
                      <li>
                        The top three results on the first page of Google
                        receive <span>54.4%</span> of all clicks.
                      </li>
                      <li>
                        Sites that load faster rank higher and see 70% longer
                        Average Sessions <span>86% of people</span> are looking
                        into Google Maps to find the direction to a location.
                      </li>
                      <li>
                        The first result on the first page of Google receives{" "}
                        <span>25% of all clicks.</span> Being on the first page
                        of Google search results will increase your brand
                        visibility and <span> click-through rate (CTR).</span>
                      </li>
                      <li>
                        Google is the most popular search engine in the world,
                        handling over <span>8.5 billion searches per day.</span>{" "}
                        That's a lot of potential traffic!
                      </li>
                    </ul>
                  </div>
                </div>
                <div className="col-lg-4">
                  <div className={styles.happy_clients}>
                    <div className={styles.happy_clients_title}>
                      <h2>
                        Imagine You Don't Need To Worry About Getting New
                        Clients Again!{" "}
                        <span className={styles.underline}>
                          Our Clients Are Happy!
                        </span>
                      </h2>
                    </div>

                    <div className="row g-3">
                      <div className="col-lg-6">
                        <img
                          src="images/happy-client.png"
                          alt="client"
                          className={`${styles.happy_client_img} img-fluid`}
                        />
                      </div>
                      <div className="col-lg-6">
                        <ul className={styles.happy_client_counter}>
                          <li>
                            <span>600+</span> Project Completed
                          </li>
                          <li>
                            <span>12+</span> Years in Business
                          </li>
                          <li>
                            <span>100%</span> Positive reviews
                          </li>
                          <li>
                            <span>92%</span> Customer Retention
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* SECTION FIVE */}
          <section className={`${styles.section_five} ${poppins.className}`}>
            <div className="container">
              <div className="row g-5">
                <div className="col-lg-5 col-sm-12">
                  <div className={styles.section_five_title}>
                    <h2>
                      How do we drive traffic, qualified leads, and conversions?
                    </h2>
                    <p>
                      Building a successful business requires bringing together
                      different pieces. The SRP team has brought good returns
                      for its customers like you, with the help of content
                      marketing. A well thought out and professionally built
                      website is the foundation of this endeavor.
                    </p>
                    <div
                      id="list-example"
                      className={`list-group ${styles.scroll_list}`}
                    >
                      <a
                        href="#list-item-1"
                        className=" list-group-item-action active"
                      >
                        Create a custom website for your brand
                      </a>
                      <a
                        href="#list-item-2"
                        className=" list-group-item-action"
                      >
                        Enhance Performance & UX
                      </a>
                      <a
                        href="#list-item-3"
                        className=" list-group-item-action"
                      >
                        High quaaty content copy
                      </a>
                      <a
                        href="#list-item-4"
                        className=" list-group-item-action"
                      >
                        Optimize for Search Engines
                      </a>
                      <a
                        href="#list-item-5"
                        className=" list-group-item-action"
                      >
                        Drive Quaaty & Niche Traffic
                      </a>
                      <a
                        href="#list-item-6"
                        className=" list-group-item-action"
                      >
                        Track Conversion, Refine & Improve
                      </a>
                    </div>
                    <button className={styles.section_five_btn}>
                      Schedule a call
                    </button>
                  </div>
                </div>
                <div className="col-lg-7 col-sm-12">
                  <div
                    className={styles.scroll_wrapper}
                    data-bs-spy="scroll"
                    data-bs-target="#list-example"
                    data-bs-smooth-scroll="true"
                    tabindex="0"
                  >
                    <div
                      id="list-item-1"
                      className={styles.scroll_item_wrapper}
                    >
                      <img
                        src="/images/scroll-banner.png"
                        alt="scroll-banner"
                        className={`img-fluid ${styles.scroll_banner_img}`}
                      />
                      <div className={styles.scroll_item}>
                        <div className={styles.scroll_item_title}>
                          <div className={styles.number}>1</div>
                          <div className={styles.content}>
                            <h2>
                              <span>Create a custom website for your</span>{" "}
                              brand
                            </h2>
                            <p>
                              A professionally made website lays the foundable
                              for building a brand by establishing a strong
                              online presence and trust online. Custom websites
                              encourage trust by demonstrating your unique
                              personality, credibility, and expertise. Show off
                              what makes you and your business so special!
                              Whether you need to sell your products or offer
                              services, a custom website design is recommended.
                              Building the perfect website can be challenging,
                              but it doesn't have to be intimidating. VOCSO team
                              helps you create a gorgeous website that truly
                              reflects your brand's story and values.
                            </p>
                          </div>
                        </div>
                        <img
                          src="/images/scroll1.png"
                          alt="scroll-banner"
                          className={`img-fluid ${styles.scroll_item_img}`}
                        />
                      </div>
                    </div>

                    <div
                      id="list-item-2"
                      className={styles.scroll_item_wrapper}
                    >
                      <div className={styles.scroll_item}>
                        <div className={styles.scroll_item_title}>
                          <div className={styles.number}>2</div>
                          <div className={styles.content}>
                            <h2>
                              <span> Enhance Performance & UX</span>
                            </h2>
                            <p>
                              To better engage your customers and empower them
                              to take action, we work on ensuring easy website
                              navigation and adapting to the device it’s being
                              viewed on. Improving website’s loading speed
                              greatly improves user experience as well help in
                              search rankings.
                            </p>
                          </div>
                        </div>
                        <img
                          src="/images/scroll2.png"
                          alt="scroll-banner"
                          className={`img-fluid ${styles.scroll_item_img}`}
                        />
                      </div>
                    </div>

                    <div
                      id="list-item-3"
                      className={styles.scroll_item_wrapper}
                    >
                      <div className={styles.scroll_item}>
                        <div className={styles.scroll_item_title}>
                          <div className={styles.number}>3</div>
                          <div className={styles.content}>
                            <h2>
                              <span>High quality content copy</span>
                            </h2>
                            <p>
                              We use E-A-T ( Expertise, Authoritativeness,
                              Trustworthiness ) - a high quality copywriting
                              strategy. We’ve spent years researching high
                              quality website content and search intent.
                            </p>
                          </div>
                        </div>
                        <img
                          src="/images/scroll3.png"
                          alt="scroll-banner"
                          className={`img-fluid ${styles.scroll_item_img}`}
                        />
                      </div>
                    </div>

                    <div
                      id="list-item-4"
                      className={styles.scroll_item_wrapper}
                    >
                      <div className={styles.scroll_item}>
                        <div className={styles.scroll_item_title}>
                          <div className={styles.number}>4</div>
                          <div className={styles.content}>
                            <h2>
                              <span>Optimize for Search Engines</span>
                            </h2>
                            <p>
                              Google is responsible for around 92.47% of all
                              internet searches worldwide. Optimizing the
                              website for google is not a choice anymore.
                            </p>
                          </div>
                        </div>
                        <img
                          src="/images/scroll4.png"
                          alt="scroll-banner"
                          className={`img-fluid ${styles.scroll_item_img}`}
                        />
                      </div>
                    </div>

                    <div
                      id="list-item-5"
                      className={styles.scroll_item_wrapper}
                    >
                      <div className={styles.scroll_item}>
                        <div className={styles.scroll_item_title}>
                          <div className={styles.number}>5</div>
                          <div className={styles.content}>
                            <h2>
                              <span>Drive Quality & Niche Traffic</span>
                            </h2>
                            <p>
                              Getting traffic to your site is hard, but it
                              doesn't have to be. VOCSO team’s effective organic
                              and paid strategy helps drive the quality traffic
                              and generate leads with high conversion ratio.
                            </p>
                          </div>
                        </div>
                        <img
                          src="/images/scroll5.png"
                          alt="scroll-banner"
                          className={`img-fluid ${styles.scroll_item_img}`}
                        />
                      </div>
                    </div>
                    <div
                      id="list-item-6"
                      className={styles.scroll_item_wrapper}
                    >
                      <div className={styles.scroll_item}>
                        <div className={styles.scroll_item_title}>
                          <div className={styles.number}>6</div>
                          <div className={styles.content}>
                            <h2>
                              <span>Track Conversion, Refine & Improve</span>
                            </h2>
                            <p>
                              Once we’ve researched the analytics data, we
                              track, refine and Improve marketing efforts by
                              amplifying what’s working and cutting off on
                              what’s not.
                            </p>
                          </div>
                        </div>
                        <img
                          src="/images/scroll6.png"
                          alt="scroll-banner"
                          className={`img-fluid ${styles.scroll_item_img}`}
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>

        {/* SECTION SIX */}
        <section className={`${styles.section_six} ${inter.className}`}>
          <div className="container">
            <div className="row">
              <div className="col">
                <div className={styles.section_six_title}>
                  <div className={styles.subheading}>
                    <span>
                      Pricing /That Help Your Website Rank High on Google
                    </span>
                  </div>
                  <h2>SEO Packages</h2>
                </div>
                <ul
                  class="nav mb-5"
                  className={styles.tab_btn_wrapper}
                  id="pills-tab"
                  role="tablist"
                >
                  <li className="nav-item" role="presentation">
                    <button
                      className="nav-link active"
                      id="pills-home-tab"
                      data-bs-toggle="pill"
                      data-bs-target="#pills-home"
                      type="button"
                      role="tab"
                      aria-controls="pills-home"
                      aria-selected="true"
                    >
                      ANNUALLY <span>(SAVE 40%)</span>
                    </button>
                  </li>
                  <li className="nav-item" role="presentation">
                    <button
                      className="nav-link"
                      id="pills-profile-tab"
                      data-bs-toggle="pill"
                      data-bs-target="#pills-profile"
                      type="button"
                      role="tab"
                      aria-controls="pills-profile"
                      aria-selected="false"
                    >
                      QUARTERLY <span>(SAVE 30%)</span>
                    </button>
                  </li>
                  <li className="nav-item" role="presentation">
                    <button
                      className="nav-link"
                      id="pills-contact-tab"
                      data-bs-toggle="pill"
                      data-bs-target="#pills-contact"
                      type="button"
                      role="tab"
                      aria-controls="pills-contact"
                      aria-selected="false"
                    >
                      MONTHLY <span>(SAVE 10%)</span>
                    </button>
                  </li>
                </ul>
              </div>
            </div>
            <div className="row">
              <div className="col-12">
                <div className="tab-content" id="pills-tabContent">
                  <div
                    className="tab-pane fade show active"
                    id="pills-home"
                    role="tabpanel"
                    aria-labelledby="pills-home-tab"
                  >
                    <div className="row g-4">
                      {packages.map((item, index) => (
                        <div className="col-4" key={index}>
                          <Package title={item.title} price={item.price} />
                        </div>
                      ))}
                    </div>
                  </div>

                  <div
                    className="tab-pane fade"
                    id="pills-profile"
                    role="tabpanel"
                    aria-labelledby="pills-profile-tab"
                  >
                    <div className="row g-4">
                      {packages.map((item, index) => (
                        <div className="col-4" key={index}>
                          <Package title={item.title} price={item.price} />
                        </div>
                      ))}
                    </div>
                  </div>

                  <div
                    className="tab-pane fade"
                    id="pills-contact"
                    role="tabpanel"
                    aria-labelledby="pills-contact-tab"
                  >
                    <div className="row g-4">
                      {packages.map((item, index) => (
                        <div className="col-4" key={index}>
                          <Package title={item.title} price={item.price} />
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
